spring:
  application:
    name: ksas-web
  datasource:
    url: jdbc:postgresql://localhost:5432/ksas
    username: postgres
    password: postgres
  flyway:
    enabled: on

jimmer:
  language: kotlin
  show-sql: true
ksas:
  security:
    anon-urls:
        - /swagger-ui.html
        - /swagger-ui/**
        - /v3/api-docs/**
        - /doc.html

